// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wfouryczkuzjmotkvpvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indmb3VyeWN6a3V6am1vdGt2cHZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4Njg3MDgsImV4cCI6MjA2MzQ0NDcwOH0.H8ZIWyuX0gY-r_TzaqVipNm9skytzqvRE56ODND9tb0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);